### ISSUE TITLE
Anki 划词助手 Chrome 版本添加时无响应，Anki 提示下列错误

### ISSUE THREAD

**Issue by ghost** [ninja33/anki-dict-helper#25]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 444, in advance
    self.server.advance()
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 203, in advance
    self.advanceClients()
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 218, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 218, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 147, in advance
    self.writeBuff += self.handler(req)
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 237, in handlerWrapper
    body = makeBytes(json.dumps(self.handler(params)))
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 451, in handler
    return getattr(self, action)(**(request.get('params') or {}))
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 471, in api_addNote
    return self.anki.addNote(params)
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 325, in addNote
    data = download(params.audio.url)
  File "C:\Users\holos\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 85, in download
    return resp.read()
  File "socket.py", line 351, in read
  File "httplib.py", line 561, in read
  File "socket.py", line 380, in read
socket.timeout: timed out

**Comment by ninja33** [comment]
你这是audio 下载超时，不知道你那里的网络情况，不好说。解决方法是不要利用插件内置的音频下载功能。你把后台选项里，选audio的那个字段空着，不要在线下载音频。音频可以事后用awesometts插件批量下载。

**Comment by ghost** [comment]
我这里默认通过 SSR 全局流量，可能是因为这个吧，空着 audio 选项问题解决，谢谢。
